#!/bin/sh

exec 2>& 1

if test -z "${SDPC_ROOT}"
then
  echo "The SDPC environment is not set"
  exit 1
fi

export SDPC_LEVEL2_PRODUCTS=$(config_setting level2.products)
export SDPC_O3PROF_MODE=$(config_setting level2.o3prof_mode)
export SDPC_O3PROF_TIME_LIMIT=$(config_setting level2.o3prof_time_limit)

export SDPC_RADREF_PRODUCTS="$(config_setting radref.products)"
export SDPC_RADREF_ENABLE=$(config_setting radref.enable)
export SDPC_RADREF_SEARCH=$(config_setting radref.search)

exec ${SDPC_ROOT}/bin/cachemon.sl "${SDPC_PIPE_DIR}/etc/cachemon/level2.cfg" -- "${SDPC_NODE_DIR}/L2"
