#!/bin/sh

exec 2>& 1

if test -z "${SDPC_ROOT}"
then
  echo "The SDPC environment is not set"
  exit 1
fi

export SDPC_RADREF_SEARCH=$(config_setting radref.search)
export SDPC_RADREF_CRON_TRIGGER_LEVEL2=$(config_setting radref.cron_trigger_level2)

export SDPC_INR_QA_TIME=$(config_setting level1b.inr_qa_time)
export SDPC_INR_QA_ENABLE=$(config_setting level1b.inr_qa_enable)
export SDPC_NRT_NUM_DAYS_KEPT=$(config_setting nrt.num_archive_days)

exec /bin/sh -c "$SDPC_ROOT/bin/pipecron.sh --service"
