#!/bin/sh

if test -z "${SDPC_ROOT}"
then
  echo "The TEMPO environment is not set" >&2
  exit 1
fi

exec 2>& 1

# FIXME - During operations, cron jobs will do this.
#         For testing purposes, do it here.
filedb -c $SDPC_ROOT/etc/filedb.cfg met --update
filedb -c $SDPC_ROOT/etc/filedb.cfg snow --update

. $SDPC_ROOT/etc/level2_products.sh

pgm="cachemon.sl"
exec ${SDPC_ROOT}/bin/$pgm "${SDPC_ROOT}/etc/level2_cachemon.cfg" -- "${SDPC_RUN_DIR}/L2" "$SDPC_LEVEL2_PRODUCTS"
