# -*- sh -*-

#---------------------------
# Enable/disable cron tasks
#---------------------------
#
# Tasks are disabled by default.
# To enable, set state = "on".

# download IMS data
state_ims=off

# download GOES data
state_goes=off

# download GEOS-CF files
state_geoscf=off

# download IERS bulletin A files
state_iers=off

# upload GOES data to ASDC
state_asdc_goes=off

# upload GEOS-CF files to ASDC
state_asdc_geoscf=off

#------------------------------
# Task configuration parameters
#------------------------------

# PDA service account for GOES imagery
pda_service_account="AO_TEMPO_SERV1@140.90.190.143"

# GEOS-CF forecast files
geoscf_source_url="https://portal.nccs.nasa.gov/datashare/gmao/geos-cf/v1/forecast"
#geoscf_source_url="https://gmao.gsfc.nasa.gov/gmaoftp/kknowlan/TEMPO"

# IERS bulletin A
iers_source_url="https://datacenter.iers.org/data/latestVersion/bulletinA.txt"

# IMS data
ims_url="ftp://sidads.colorado.edu"
ims_dir="pub/DATASETS/NOAA/G02156/GIS/1km"

# ASDC dropbox account: user@host
asdc_dropbox="tempo@xfr140.larc.nasa.gov"
#asdc_dropbox="jhouck@waps.cfa.harvard.edu"

