# To have rsyslog manage messages from cachemon in a separate log file,
# do the following:
# 1. Put this file in e.g. /etc/rsyslog.d/00-cachemon.conf
# 2. Create the log file, e.g.:
#      # mkdir /var/log/custom
#      # touch /var/log/custom/cachemon.log
# 3. restart rsyslogd:
#      # /etc/init.d/rsyslog restart

if $programname == 'cachemon' then /var/log/custom/cachemon.log
if $programname == 'cachemon' then ~
