#--BEGIN_HEADER--
# This file specifies actions to be taken by cachemon when it
# detects the existence of the file: $SDPC_PIPE_DIR/ctrl/disable
#
# Configuration line syntax:
#   <service>:<config-string>
#
# where <service> is either 'default' or the name of
#                 a cachemon-based service.
# and <config-string> is a colon-delimited configuration
#                 string as described below.
#
#  Supported types of <config-string>:
#  1)  value: continue
#     action: Do nothing
#
#  2)  value: disable
#     action: Disable service immediately and unconditionally.
#
#  3)  value: match:<regex>
#     action: Disable service upon arrival of a file with
#             a basename that matches the provided regular
#             expression. If <regex> is 'default', then the
#             regular expression is TEMPO_RAD_L\d{1}_[^G]*G01.
#
#  4)  value: time:<tstring>:<regex>
#     action: Disable service upon arrival of a file with
#             a basename that contains a substring that
#             lexically follows the literal string, <tstring>,
#             provided in the second field. The regular expression
#             <regex> is used to extract the basename's substring
#             for comparison.  If <regex> is 'default', then
#             the regular expression is:
#                TEMPO_RAD_L\d{1}_V\d{2}_(\d{8}T\d{6}Z)_S\d{3}G\d{2},
#             so that the substring is the filename's timestamp.
#----------------------------------------------------------------------
#--END_HEADER--

# level1a service:
#   Disable upon arrival of the next file matching
#   the default regex: TEMPO_RAD_L\d{1}_[^G]*G01

level1a:match:default

# All other services:
#   Disable immediately

default:disable
