# Filter configuration for collectd(1).
#
# filecount plugin configuration.
# Installation:
#  1) copy this file into /etc/collectd/collectd.conf.d
#  2) /etc/init.d/collectd restart

LoadPlugin filecount

<Plugin "filecount">
   <Directory "/vex/d0/sdpc_run_dir/L1/radiance/inr_out/granules/">
     Instance "radiance-inr-out"
   </Directory>
   <Directory "/vex/d0/sdpc_run_dir/L2/out">
     Instance "L2-out"
     IncludeHidden true
   </Directory>
   <Directory "/vex/d0/sdpc_run_dir/L2/repro">
     Instance "L2-repro"
   </Directory>
   <Directory "/vex/d0/archive/L2/incoming">
     Instance "archive-L2-incoming"
     IncludeHidden true
   </Directory>
   <Directory "/vex/d0/archive/L3/incoming">
     Instance "archive-L3-incoming"
     IncludeHidden true
   </Directory>
   <Directory "/vex/d0/archive/L2/1">
     Instance "archive-L2-v1"
   </Directory>
   <Directory "/vex/d0/archive/L3/1">
     Instance "archive-L3-v1"
   </Directory>
</Plugin>
