#
# The GEOSCF parameters are used by libclim
#
[GEOSCF]
GEOSCF_Climatology_Files = $SDPC_REFDATA_DIR/climatology/monthly_by_hour/GEOS-CF_NRT.month%02d_%02dz_reorder.nc4
#-- version 1:
GEOSCF_Forecast_Files    = $SDPC_ANCILLARY_ROOT/var/geoscf/%4d/%03d/GEOS-CF.v01.fcst.sat_inst_1hr_r721x361_v72.%4d%02d%02d_12z_%4d%02d%02d_%02d00z_reorder.nc4
#-- version 2:
#GEOSCF_Forecast_Files   = $SDPC_ANCILLARY_ROOT/var/geoscf_v2/%4d/%03d/GEOS.cf.fcst.sat_inst_1hr_reg_L721x361_v72.%4d%02d%02d_09z_%4d%02d%02d_%02d00z.V01_reorder.nc4
GEOSCF_Analysis_Files    = none
GEOSCF_Pressure_Grid     = $SDPC_REFDATA_DIR/climatology/GEOS-Chem_72_layer_vertical_grid.nc
#
# Cloud_Climatology isn't a GEOS-CF product, but it's convenient to put it here
#
Cloud_Climatology        = $SDPC_REFDATA_DIR/climatology/omcldrr_pressure.nc

#
# The GLER parameters are used by libgler
#
[GLER]
GLER_Land_File_Pattern  = $SDPC_REFDATA_DIR/gler/%dnm/modis_land_v5_d???.nc
GLER_Snow_File_Pattern  = $SDPC_REFDATA_DIR/gler/%dnm/modis_snow_v4_d???.nc
GLER_Ocean_File_Pattern = $SDPC_REFDATA_DIR/gler/%dnm/modis_ocean_v2_d???.nc
