#!/bin/sh

exec 2>& 1

if test -z "${SDPC_ROOT}"
then
  echo "The SDPC environment is not set"
  exit 1
fi

export SDPC_DESTRIPE_TG=$(config_setting level2.destripe_tg)
export SDPC_BKGCORR_TG=$(config_setting level2.bkgcorr_tg)

dbfile_level1="$(config_setting dbfile.level1)"
if ! test -f "$dbfile_level1" ; then
   dbfile_level1="$SDPC_ARCHIVE_DBFILE"
fi
export SDPC_ARCHIVE_DBFILE_L1="$dbfile_level1"

exec register.py --service
