#!/bin/sh

exec 2>& 1

if test -z "${SDPC_ROOT}"
then
  echo "The SDPC environment is not set"
  exit 1
fi

# When SDPC_IOC_SOCARCHIVE_DIR is set, use that, otherwise use this default
: "${SDPC_IOC_SOCARCHIVE_DIR:=/tempo/ioc/cacheroot/socarchive}"

sdpc_dest_dir="$SDPC_ARCHIVE_DIR/raw"

echo "iocpullraw $SDPC_IOC_SOCARCHIVE_DIR -> $sdpc_dest_dir"

exec pull_raw.sl --register $SDPC_IOC_SOCARCHIVE_DIR $sdpc_dest_dir
