#!/bin/sh

exec 2>& 1

if test -z "${SDPC_ROOT}"
then
  echo "The SDPC environment is not set"
  exit 1
fi

cd $SDPC_INR_RUN_DIR

pgm="PipelineInterface"
exec ${INRSW_INSTALL_DIR}/bin/$pgm config/TempoPipelineInterfaceSAO.conf
