#ifndef __WAVECAL_INCLUDE__
#define __WAVECAL_INCLUDE__ 1

#include <libconfig.h>

/** @file wavecal.h
 *  @brief Wavelength calibration
 *
 * This module provides an interface for performing wavelength calibration.
 */

typedef struct Wavecal_Type Wavecal_Type;

typedef struct
{
   double fill_value;   /**< fill value for spectrum values, radiance or irradiance */
}
Wavecal_Config_Type;

typedef struct
{
   const double *wave;
   /**< pointer to calibrated wavelength grid.
    * Storage for this array is managed internally and
    * must not be freed by the calling program.
    */
   const double *wave_params;
   /**< pointer to array of wavelength grid parameters
    * Storage for this array is managed internally and
    * must not be freed by the calling program.
    */
   size_t num_wave_params;
   /**< number of wavelength grid parameters */

   const double *model;        /**< best fit model */
   const double *spec_scaled;  /**< scaled spectrum that was fitted */
   const double *residuals;    /**< weighted fit residuals */
   double bestnorm;    /**< best fit statistic */
   int num_fit;        /**< number of pixels fitted */
   int nfev;           /**< number of objective function evaluations */
   int opt_status;     /**< optimizer status code */
}
Wavecal_Result_Type;

typedef struct
{
   const char *name;   /**< term name */
   double *value;      /**< term value vs wavelength */
   size_t num_values;  /**< number of wavelength grid points */
}
Wavecal_Term_Info_Type;

/** Free memory associated with a \a Wavecal_Type object
 * @param   A pointer to a \a Wavecal_Type object generated by
 *          \a wavecal_open.
 */
extern void wavecal_close (Wavecal_Type *wct);

/** Create an \a Wavecal_Type object for spectra with \a num_wave
 * wavelength points.
 * @param cfg        Pointer to an open \a config_t structure initialized
 *                   with an appropriate configuration file.
 * @param cfg_name   Name of configuration file parameter group governing
 *                   the spectrum to be calibrated.
 * @param max_num_wave  Maximum number of wavelength points in each spectrum to be calibrated.
 * @param is_irradiance  Integer indicating the type of spectra to be calibrated
 *                       1 means irradiance, 0 means radiance.
 * @return A valid \a Wavecal_Type pointer on success, NULL on error.
 */
extern Wavecal_Type *wavecal_open (config_t *cfg, const char *cfg_name,
                                   int max_num_wave, int is_irradiance);

/** Query the number of wavelength parameters
 * @param  wct   Pointer to \a Wavecal_Type object initialized by \a wavecal_open
 * @return the number of wavelength parameters on success, -1 on error.
 */
extern int wavecal_num_wave_params (const Wavecal_Type *wct);

/** Query the fit window offset and width
 * @param  wct        Pointer to \a Wavecal_Type object initialized by \a wavecal_open
 * @param  start_pix  Address to hold the window offset (NULL is ok)
 * @param  num_pix    Address to hold the window width (NULL is ok)
 * @return 0 on success, -1 on error
 */
extern int wavecal_query_feature_window (const Wavecal_Type *wct, int *start_pix, int *num_pix);

/** Query the initial wavelength scale parameters
 * @param  wct[in]    Pointer to \a Wavecal_Type object initialized by \a wavecal_open
 * @param  wave[in]   Pointer to initial wavelength grid
 * @param  wave_params[out]  Initial wavelength parameter values
 * @return 0 on success, -1 on error
 *
 * It is assumed that the array sizes are consistent with the values
 * provided to \a wavecal_open().
 */
extern int wavecal_get_initial_params (Wavecal_Type *wct, const double *p_wave,
                                       double *wave_params);

/** Perform wavelength calibration on a single spectrum
 * @param  wct      Pointer to a \a Wavecal_Type object initialized by
 *                  \a wavecal_open.
 * @param  xtrack   Cross-track array index of the spectrum to calibrate
 * @param  wave     Pointer to initial wavelength grid
 * @param  spec     Pointer to spectrum values, radiance or irradiance
 * @param  specerr  Pointer to array of spectrum uncertainties
 * @param  pqf      Pointer to array of pixel quality flags (0 means good)
 * @param  config   Pointer to object of type \a Wavecal_Config_Type
 *                  containing additional control/configuration parameters.
 * @param  wave_params  Pointer to array of wavelength fit parameters
 * @param  result   Pointer to object of type \a Wavecal_Result_Type
 *                  containing calibration results. (NULL is ok)
 * @return -1 on error, 0 when the fit succeeds, 1 when the fit fails
 *
 * When the fit fails, the wave_params array contains the initial
 * parameter values, which should normally correspond to the default
 * wavelength grid.
 */
extern int
wavecal_fit (Wavecal_Type *wct, int xtrack,
             const double *wave, const double *spec, const double *specerr,
             const unsigned int *pqf, const Wavecal_Config_Type *config,
             double *wave_params, Wavecal_Result_Type *result);

enum
{
   WAVECAL_FIT_ERROR = -1,
   WAVECAL_FIT_GOOD = 0,
   WAVECAL_FIT_BAD = 1
};

/** Query fit terms in succession
 * @param  wct      Pointer to a \a Wavecal_Type object initialized by
 *                  \a wavecal_open.
 * @param  nth      zero-based index of the term of interest
 * @param  info     Pointer to a \a Wavecal_Term_Info_Type object
 *
 * On success, returns the index of the next term, or zero,
 * if there are no more terms.
 * On error, returns -1.
 *
 * The \a Wavecal_Term_Info_Type structure contains pointers to
 * the internal arrays containing the term's value on the target
 * spectrum's wavelength grid.  Note that these pointers are
 * valid only until the \a Wavecal_Type object is closed.
 */
extern int wavecal_query_term (const Wavecal_Type *wct, int nth,
                               Wavecal_Term_Info_Type *info);

#endif
