#!/bin/sh

exec 2>& 1

if test -z "${SDPC_ROOT}"
then
  echo "The SDPC environment is not set"
  exit 1
fi

dropbox=$(config_setting asdc.dropbox)
update_interval=$(config_setting asdc.update_interval)

export SDPC_ASDC_LIMIT=$(config_setting asdc.max_num_files)

exec ${SDPC_ROOT}/bin/asdc_transfer.py --wait $update_interval --script-fmt "asdc_%s.sh" $dropbox
