#!/bin/sh

exec 2>& 1

if test -z "${SDPC_ROOT}"
then
  echo "The SDPC environment is not set"
  exit 1
fi

export SDPC_DIAGNOSTIC_INDEX=$(config_setting level1a.diagnostic_index)

dbfile_level0="$(config_setting dbfile.level0)"
if ! test -f "$dbfile_level0" ; then
   dbfile_level0="$SDPC_ARCHIVE_DBFILE"
fi
export SDPC_ARCHIVE_DBFILE_L0="$dbfile_level0"

# select_irr.py requires SDPC_ARCHIVE_DBFILE_L1
export SDPC_ARCHIVE_DBFILE_L1="$SDPC_ARCHIVE_DBFILE"

exec ${SDPC_ROOT}/bin/cachemon.sl "${SDPC_PIPE_DIR}/etc/cachemon/level1a.cfg" -- "${SDPC_NODE_DIR}/L0"
