#! /bin/sh

# 0. This script is run by cachemon, triggered by the appearance
#    of a newly completed geolocated radiance file in the INR
#    output cache.
#
# 1. The script first runs a batch process (level2_prep.sh) on a compute
#    node to finish Level 1 processing (post-INR calculations,
#    polarization correction, wavelength calibration), and generate
#    the cloud product.
#
# 2. Once the cloud product is available, the remaining Level 2
#    products are generated by running level2_dispatch.sh
#
# On error, a tar file is stored in L1/repro
#
#--------------------------------------------------------------------

set -e
set -u

# If SDPC_LEVEL2_PRODUCTS is not set, define it
: "${SDPC_LEVEL2_PRODUCTS:=NONE}"

# Note that the radiance file name be "hidden" (may begin with a ".").

if test $# -ne 2 ; then
  echo "Usage: $0 <rad-path> <l1_run_dir>"
  exit 1
fi

rad_path="$1"
l1_run_dir="$2"

PROGNAME="$(basename $0)"
error_exit()
{
   echo "${PROGNAME}[$$]: ${1:-'Unknown Error'}" 1>&2
   exit 1
}

trap error_exit ERR

log_message()
{
   printf "${PROGNAME}[$$]: $1\n"
}

test -r $rad_path || error_exit "$LINENO: cannot access granule: $rad_path"
test -d "$SDPC_ROOT" || error_exit "$LINENO: cannot access SDPC_ROOT directory: $SDPC_ROOT"

export PATH="$SDPC_ROOT/bin:$PATH"

# SDPC_RUN_DIR need not exist on this machine at this point.
# However, it must be defined, and the value will be used
# in the processing directory path on the compute nodes.
: "${SDPC_RUN_DIR:?SDPC_RUN_DIR not set}"

# Parse the path to the post-INR radiance file
rad_basename=$(basename "$rad_path" .nc| sed -e s"/.Smoothed$//" -e s"/^[.]//")

# construct granule label string for slurm job names
export SDPC_GRANULE_LABEL="${rad_basename}"

# FIXME - in operations, a cron job should handle this DB update, e.g. 1x per day
# For testing, we'll update it here, because the irr file may be newly created
filedb -c $SDPC_ROOT/etc/filedb.cfg tempo:irr --update

cache_uncompressed_snow_file()
{
   path=$1

   file_sans_gz=$(basename $path .gz)

   cache_dir="$SDPC_RUN_DIR_MASTER/cache/snow"
   if ! test -d $cache_dir ; then
      mkdir -p $cache_dir || error_exit "$LINENO: cannot create directory: $cache_dir"
   fi

   snow_file="$cache_dir/$file_sans_gz"
   if ! test -f "$snow_file" ; then
      gunzip -c $path > "$snow_file" || error_exit "$LINENO: uncompressing file into $cache_dir"
   fi
}

# Generate file list file on master node
irr_file=$(filedb -c $SDPC_ROOT/etc/filedb.cfg tempo:irr --find --header "$rad_path")
snow_file=$(filedb -c $SDPC_ROOT/etc/filedb.cfg snow --find --header "$rad_path")
cache_uncompressed_snow_file $snow_file
met_file_path_synth=$(filedb -c $SDPC_ROOT/etc/filedb.cfg met:synth --find --header "$rad_path")
met_file_path_hires=$(filedb -c $SDPC_ROOT/etc/filedb.cfg met:hires --find --header "$rad_path")
met_file_path_lores=$(filedb -c $SDPC_ROOT/etc/filedb.cfg met:lores --find --header "$rad_path")
granule_dir=$(dirname "$rad_path")
file_list_file="$granule_dir/${rad_basename}.lis"
cat <<EOF > $file_list_file
rad_path=${rad_path}
irr_file=${irr_file}
snow_file=${snow_file}
met_file_path_synth=${met_file_path_synth}
met_file_path_hires=${met_file_path_hires}
met_file_path_lores=${met_file_path_lores}
EOF

log_message "start level2_prep.sh: $SDPC_GRANULE_LABEL"

# Run the post-INR pipeline to prepare for L2 product generation:
job_prep_l2="L2-pre:${SDPC_GRANULE_LABEL}"
sbatch --wait --job-name=$job_prep_l2 --chdir $l1_run_dir \
        --nodes=1-1 --ntasks=8 \
        level2_prep.sh "${rad_basename}.nc" "$file_list_file"

log_message "finished level2_prep.sh: $SDPC_GRANULE_LABEL"

# If no Level 2 products were requested, we're done
if test x"$SDPC_LEVEL2_PRODUCTS" = x"NONE"; then
  exit 0
fi

# When Level 2 products have been requested, a tar file notice
# should have been created.  The tar file provides the data
# products necessary to generate Level2 data products

# The --wait above ensures that we don't get to here until
# this tar file notice has been created -- and there's no point in
# proceeding further if we don't have it.
tar_file_notice="$SDPC_RUN_DIR_MASTER/L2/incoming/${rad_basename}.tar"
if ! test -f "$tar_file_notice" ; then
  error_exit "*** Error: level2_prep.sh failed: $rad_basename"
fi

level2_dispatch.sh $tar_file_notice
