#!/bin/sh

exec 2>& 1

if test -z "${SDPC_ROOT}"
then
  echo "The SDPC environment is not set"
  exit 1
fi

export SDPC_LEVEL2_PRODUCTS=$(config_setting nrt.products)

# Set sqlite database to use for radiance reference file lookup
radref_dbfile=$(config_setting nrt.radref_dbfile)
if test -z "$radref_dbfile" ; then
   radref_dbfile="$SDPC_ARCHIVE_DBFILE"
fi
export SDPC_NRT_RADREF_DBFILE="$radref_dbfile"
export SDPC_NRT_PROCESSING_VERSION=$(config_setting nrt.processing_version)
export SDPC_NRT_PARTITION=$(config_setting nrt.partition)

exec ${SDPC_ROOT}/bin/cachemon.sl "${SDPC_PIPE_DIR}/etc/cachemon/level2_nrt.cfg" -- "${SDPC_NODE_DIR}/L2"
