#! /bin/sh

# FIXME (someday when doxygen works better):
# Because doxygen fails when parsing fortran include
# files that contain only variable declarations,
# this filter turns those files into modules that
# doxygen can process correctly.  Unfortunately,
# doxygen will then proceed to 'include' the filtered
# text into the parent .f90 source before parsing.
# The parent file then fails to parse because Fortran
# doesn't allow nested modules.  I avoid the latter
# problem by using another doxygen filter to comment
# out the relevant include lines in the parent .f90 file.

file=$1
bn=`basename $file .inc`

modname="__autogenerated_${bn}"
echo "!> Autogenerated from ${bn}.csv.  Do not edit."
echo "!! @file"
echo "module $modname"
cat $file
echo "end module\n"
