
all:
	cd src; $(MAKE) all

check:
	cd tests; $(MAKE) check

docs:
	cd doc; $(MAKE) docs

install:
	cd src; $(MAKE) install

clean:
	cd src; $(MAKE) clean
	cd tests; $(MAKE) clean
	cd doc; $(MAKE) clean

distclean:	clean
	cd src; $(MAKE) distclean
	cd tests; $(MAKE) distclean
	cd doc; $(MAKE) distclean
