
all:
	cd src; $(MAKE) all

check:
	cd tests; $(MAKE) check

install:
	cd src; $(MAKE) install

clean:
	cd src; $(MAKE) clean
	cd tests; $(MAKE) clean

distclean:	clean
	cd src; $(MAKE) distclean
	cd tests; $(MAKE) distclean
