#!/bin/sh

exec 2>& 1

if test -z "${SDPC_ROOT}"
then
  echo "The SDPC environment is not set"
  exit 1
fi

livestream_dir=$(config_setting ioc.livestream_dir)

sdpc_dest_dir="$SDPC_RUN_DIR_MASTER/stage/level0/spool"
if ! test -d $sdpc_dest_dir ; then
  mkdir -p $sdpc_dest_dir
fi

echo "iocpull $livestream_dir -> $sdpc_dest_dir"

exec move_file_stream.sl $livestream_dir $sdpc_dest_dir
