#!/bin/sh

exec 2>& 1

if test -z "${SDPC_ROOT}"
then
  echo "The SDPC environment is not set"
  exit 1
fi

dbfile_level1="$(config_setting dbfile.level1)"
if ! test -f "$dbfile_level1" ; then
   dbfile_level1="$SDPC_ARCHIVE_DBFILE"
fi
export SDPC_ARCHIVE_DBFILE_L1="$dbfile_level1"

export SDPC_RADREF_VERSION="$SDPC_PROCESSING_VERSION"
export SDPC_DSTR_VERSION="$SDPC_PROCESSING_VERSION"
export SDPC_NRT_PROCESSING_VERSION=$(config_setting nrt.processing_version)

export SDPC_RADREF_ENABLE=$(config_setting radref.enable)
export SDPC_RADREF_CRON_TRIGGER_LEVEL2=$(config_setting radref.cron_trigger_level2)
export SDPC_DESTRIPE_TG=$(config_setting level2.destripe_tg)
export SDPC_BKGCORR_TG=$(config_setting level2.bkgcorr_tg)

exec ${SDPC_ROOT}/bin/cachemon.sl "${SDPC_PIPE_DIR}/etc/cachemon/level3.cfg"
