
all:
	cd src; $(MAKE) all

check:
	cd tests; $(MAKE) check

docs:
	#cd docs; $(MAKE) docs

install:
	cd src; $(MAKE) install
	cd slurm; $(MAKE) install

clean:
	cd src; $(MAKE) clean

distclean:	clean
	cd src; $(MAKE) distclean
