#!/bin/sh

exec 2>& 1

if test -z "${SDPC_ROOT}"
then
  echo "The SDPC environment is not set"
  exit 1
fi

exec L0_format --register \
               --Version "$SDPC_PROCESSING_VERSION" \
               --logdir "${SDPC_RUN_DIR_MASTER}/incoming/log" \
               --archive "$SDPC_ARCHIVE_DIR" "${SDPC_ROOT}/etc/l0_format.cfg"
