#!/bin/sh

exec 2>& 1

if test -z "${SDPC_ROOT}"
then
  echo "The SDPC environment is not set"
  exit 1
fi

export SDPC_RADIANCE_WAVECAL=$(config_setting level1b.wavecal)
export SDPC_RADIANCE_WAVECAL_NTASKS=$(config_setting level1b.wavecal_ntasks)
export SDPC_RADIANCE_POLCORR=$(config_setting level1b.polcorr)
export SDPC_RADIANCE_POSTINR=$(config_setting level1b.postinr)
export SDPC_RADIANCE_POSTINR_ONLY=$(config_setting level1b.postinr_only)
export SDPC_DIAGNOSTIC_INDEX=$(config_setting level1b.diagnostic_index)

export SDPC_SOLCAL_CACHE_ENABLE=$(config_setting level1a.solcal_cache_enable)
export SDPC_SOLCAL_CACHE_PRODUCTS=$(config_setting level1a.solcal_cache_products)

export SDPC_IRR_SELECT_WINDOW=$(config_setting level1b.irr_select_window)

dbfile_level1="$(config_setting dbfile.level1)"
if ! test -f "$dbfile_level1" ; then
   dbfile_level1="$SDPC_ARCHIVE_DBFILE"
fi
export SDPC_ARCHIVE_DBFILE_L1="$dbfile_level1"

exec ${SDPC_ROOT}/bin/cachemon.sl "${SDPC_PIPE_DIR}/etc/cachemon/level1b.cfg" -- "${SDPC_NODE_DIR}/L1"
